### ISSUE TITLE
关键词提取模块使用报错

### ISSUE THREAD

**Issue by xxyp** [yangyaofei/nlpir-python#49]
from nlpir.native import KeyExtract
from nlpir import native, PACKAGE_DIR, clean_logs, ictclas

for word, pos in ictclas.segment(test_str, pos_tagged=True):
    print(word, pos)
json_out = native.OUTPUT_FORMAT_JSON
def get_key_extract(encode=native.UTF8_CODE):
    return KeyExtract(encode=encode)
key_extract = get_key_extract()
word_lists = key_extract.get_key_words("法国启蒙思想家孟德斯鸠曾说过")
print(word_lists)

分词功能可以正常使用，但是关键词提取的时候异常退出，请问这是什么问题呢
Process finished with exit code -1073740940 (0xC0000374)

**Comment by yangyaofei** [comment]
请提供 nlpir-python 版本信息, 是否更新证书, 操作系统信息

**Comment by xxyp** [comment]
nlpir-python版本是0.9.14，证书是从github前两天刚下载的，操作系统windows10 amd64

**Comment by yangyaofei** [comment]
```python3
from nlpir import key_extract
print(key_extract.get_key_words("法国启蒙思想家孟德斯鸠曾说过"))
```

直接调用封装好的接口测试没有问题

**Comment by xxyp** [comment]
直接调用还是报一样的错误，系统的问题？

**Comment by yangyaofei** [comment]
可能为缺少vc++库等问题，
- 建议重装nlpir-python
- 重新导入证书
- 对照 github action windows 安装的依赖安装对应依赖

自动化测试是通过的，应该不是库本身的问题

**Comment by xxyp** [comment]
嗯嗯好的，我再看一下，谢谢
